name: Manual Greeting

on:
  workflow_dispatch:
    inputs:
      student_name:
        description: "Имя ученика для приветствия"
        required: true
        default: "Школьник"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: |
          echo "Привет, ${{ github.event.inputs.student_name }}!"
          echo "Номер запуска: ${GITHUB_RUN_NUMBER}"